[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino

; 設定序列埠監聽的鮑率
monitor_speed = 115200

; 更改分割區配置，騰出足夠的空間給模型與應用程式
board_build.partitions = huge_app.csv

; 啟動編譯參數，強制開啟外部 PSRAM 支援
build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue

lib_deps =
    ; 引入社群維護的 ESP32 TensorFlow Lite Micro 函式庫
    tanakamasayuki/TensorFlowLite_ESP32 @ ^1.0.0
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11

    